name: "Build"

on:
  push:
    tags:
       - '*'
  pull_request:
    tags:
      - '*'
  workflow_dispatch:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version that should be used to compile the code [8, 16, 17]'
        required: true
        type: number

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          
      - name: Run build with Gradle wrapper
        run: ./gradlew build --scan
        
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
